export const DOG_BREEDS = [
  "Border Collie",
  "German Shepherd",
  "Golden Retriever",
  "Labrador Retriever",
  "French Bulldog",
  "Bulldog",
  "Poodle",
  "Beagle",
  "Rottweiler",
  "German Shorthaired Pointer",
  "Dachshund",
  "Pembroke Welsh Corgi",
  "Australian Shepherd",
  "Yorkshire Terrier",
  "Boxer",
  "Cavalier King Charles Spaniel",
  "Doberman Pinscher",
  "Great Dane",
  "Miniature Schnauzer",
  "Siberian Husky",
  "Shih Tzu",
  "Boston Terrier",
  "Bernese Mountain Dog",
  "Pomeranian",
  "Havanese",
  "Shetland Sheepdog",
  "Brittany",
  "English Springer Spaniel",
  "Cocker Spaniel",
  "Border Terrier",
  "Maltese",
  "Chihuahua",
  "Vizsla",
  "Weimaraner",
  "Belgian Malinois",
  "Newfoundland",
  "Collie",
  "Basset Hound",
  "West Highland White Terrier",
  "Rhodesian Ridgeback",
  "Dalmatian",
  "Akita",
  "St. Bernard",
  "Bullmastiff",
  "Airedale Terrier",
  "Shiba Inu",
  "Portuguese Water Dog",
  "Scottish Terrier",
  "Irish Wolfhound",
  "Great Pyrenees",
  "Scottish Deerhound",
];
