"""001_initial

Revision ID: 521af6a1e467
Revises: 
Create Date: 2026-02-10 14:09:50.725593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '521af6a1e467'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('animals',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('public_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', 'RABBIT', 'BIRD', 'OTHER', name='species_enum'), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='sex_enum'), nullable=False),
    sa.Column('status', sa.Enum('INTAKE', 'AVAILABLE', 'RESERVED', 'ADOPTED', 'FOSTERED', 'RETURNED', 'DECEASED', 'TRANSFERRED', name='animal_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code')
    )
    op.create_index(op.f('ix_animals_organization_id'), 'animals', ['organization_id'], unique=False)
    op.drop_table('sqlpet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_organization_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_table('organizations')
    # ### end Alembic commands ###
